theme: jekyll-theme-midnight
title: ğŸ¶ JJ van Zon ğŸ’»
plugins:
  - jekyll-relative-links
  - jekyll-default-layout
  - jekyll-seo
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md